export const protectedPaths = [
    "/profile",
    "/accommodation-proofs",
    "/dashboard",
    "/chat",
    "/derantau-admin-profile",
    "/events",
    "/financial-proofs",
    "/health-clearance-info",
    "/hub-owner-profile",
    "/hubs",
    "/nomad-profile",
    "/regions",
    "/reviews",
    "/settings",
    "/states",
    "/visa-applications",
    "/work-contract-proofs",
]

